spring.application.name=autoescuela
server.port=8080

spring.datasource.url=null
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.exclude=static/**,public/**,templates/**
spring.devtools.restart.trigger-file=.restartTrigger

logging.level.org.springframework.web=DEBUG

jwt.secret=Clave-Muy-Larga
jwt.expiration=3600000

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB